export const testdata = {
    "Symbol": "AKAM",
    "AssetType": "Common Stock",
    "Name": "Akamai Technologies, Inc",
    "Description": "Akamai Technologies, Inc. provides cloud services for delivering, optimizing, and securing content and business applications over the Internet in the United States and internationally. It provides Web Application Protector to safeguard web assets from web application and distributed denial of service; Kona Site Defender, a cloud security solution; Bot Manager to identify bots and categorize bots based on business or IT impact; Edge DNS, which translates human-readable domain names into numerical IP addresses; Site Shield that prevents attacker from directly targeting the application origin and forces traffic to go through its network, where attack can be better detected and mitigated; identity Cloud, a customer identity access management solution; Prolexic Routed to protect web- and IP-based application; and Client Reputation that assigns risk scores to malicious IP address and enables customers to take action on individual clients. It also offers Enterprise Application Access that enables adaptive access to application; Enterprise Threat Protector to enable enterprise security teams to identify, block, and mitigate targeted attack; Ion, a suite of intelligent performance optimization tool and control; Dynamic Site Accelerator to accelerate and secure interactive website; Image Manager that automatically optimizes online images; CloudTest to conduct load testing and other analysis of website in a pre-production environment; and mPulse that provides real-time website performance data for customers to enhance their digital experiences. In addition, the company provides Aura Managed CDN, DNS Infrastructure, and security and personalization service; and adaptive delivery, download delivery, media service live, and media analytic solutions, as well as NetStorage, a cloud storage solution. It sells its solutions through direct sales and service organizations; and various channel partners. The company was founded in 1998 and is headquartered in Cambridge, Massachusetts.",
    "Exchange": "NASDAQ",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "Technology",
    "Industry": "Software-Infrastructure",
    "Address": "145 Broadway, Cambridge, MA, United States, 02142",
    "FullTimeEmployees": "8155",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2020-09-30",
    "MarketCapitalization": "18361534464",
    "EBITDA": "987326016",
    "PERatio": "33.0666",
    "PEGRatio": "1.6448",
    "BookValue": "25.231",
    "DividendPerShare": "None",
    "DividendYield": "0",
    "EPS": "3.411",
    "RevenuePerShareTTM": "19.257",
    "ProfitMargin": "0.1801",
    "OperatingMarginTTM": "0.2184",
    "ReturnOnAssetsTTM": "0.0615",
    "ReturnOnEquityTTM": "0.1479",
    "RevenueTTM": "3123984896",
    "GrossProfitTTM": "1905993000",
    "DilutedEPSTTM": "3.411",
    "QuarterlyEarningsGrowthYOY": "0.131",
    "QuarterlyRevenueGrowthYOY": "0.117",
    "AnalystTargetPrice": "126.86",
    "TrailingPE": "33.0666",
    "ForwardPE": "19.4932",
    "PriceToSalesRatioTTM": "5.7506",
    "PriceToBookRatio": "4.3223",
    "EVToRevenue": "6.088",
    "EVToEBITDA": "16.5167",
    "Beta": "0.468",
    "52WeekHigh": "121.11",
    "52WeekLow": "75.1801",
    "50DayMovingAverage": "106.5297",
    "200DayMovingAverage": "107.5635",
    "SharesOutstanding": "162704992",
    "SharesFloat": "159946721",
    "SharesShort": "8374604",
    "SharesShortPriorMonth": "10259297",
    "ShortRatio": "5.09",
    "ShortPercentOutstanding": "0.05",
    "ShortPercentFloat": "0.0588",
    "PercentInsiders": "2.119",
    "PercentInstitutions": "93.551",
    "ForwardAnnualDividendRate": "0",
    "ForwardAnnualDividendYield": "0",
    "PayoutRatio": "0",
    "DividendDate": "None",
    "ExDividendDate": "None",
    "LastSplitFactor": "None",
    "LastSplitDate": "None"
  }

